/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        System.out.println("hello");
        Restaurant restaurant=new Restaurant("yazan",3,"$$");
        Review review =new Review("yazan","yazan",0);
        System.out.println(review);
        System.out.println(restaurant);

    }
}
