/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
    @Test void testResturant() {
        String name ="yazan";
        int starts=3;
        String price ="$$";
        Restaurant test = new Restaurant(name,starts,price);

        assertEquals("Restaurant{name='yazan', starts=3, price='$$'}",test.toString(),"xxxxxxxxxxxxxxxx");
    }
    @Test void testReview() {
         String body="yazan";
          String author="yazan";
          int stars=3;
        Review test = new Review (body,author,stars);

        assertEquals("Review{" +
                "body='" + body + '\'' +
                ", author='" + author + '\'' +
                ", stars=" + stars +
                '}',test.toString(),"xxxxxxxxxxxxxxxx");
    }
}


